# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='AuthenticationApp.Student'),
        ),
    ]
