# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0004_comment_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cid',
        ),
    ]
