# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0002_auto_20170117_1953'),
        ('GroupsApp', '0006_comment_cid'),
    ]

    operations = [
    ]
