# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0007_auto_20161204_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(default=None, related_name='project_groups', to='ProjectsApp.Project'),
        ),
    ]
