# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0007_merge_20170125_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='requests',
        ),
    ]
