# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0007_group_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
    ]
