# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0010_auto_20170124_1638'),
        ('GroupsApp', '0002_auto_20170117_1953'),
    ]

    operations = [
    ]
