# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0007_merge_20170204_2101'),
        ('GroupsApp', '0008_auto_20170204_2218'),
        ('GroupsApp', '0012_auto_20170125_1613'),
    ]

    operations = [
    ]
