# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0014_auto_20170213_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_skills',
            field=models.TextField(null=True),
        ),
    ]
