# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
