# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='programmingLanguage',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='speciality',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='yearsOfExperience',
            field=models.IntegerField(default=0),
        ),
    ]
