# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0003_merge_20161128_1926'),
        ('ProjectsApp', '0003_merge_20161128_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='CompaniesApp.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='experience',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
