# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('ProjectsApp', '0003_auto_20161205_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
    ]
