# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0004_project_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name=b'date updated'),
        ),
    ]
