# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectsApp', '0004_auto_20161203_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='project',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project'),
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
