# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20170304_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='project_set', to='ProjectsApp.ProgrammingLanguage'),
        ),
    ]
