# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subComments',
            field=models.ManyToManyField(related_name='_comment_subComments_+', to='CommentsApp.Comment'),
        ),
    ]
