# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_auto_20161111_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommentsApp.Comment')),
            ],
        ),
    ]
