# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='members',
        ),
    ]
