# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=500, null=True)),
                ('contact', models.IntegerField(max_length=10, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('almamater', models.CharField(max_length=100, null=True)),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
