# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
