# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0001_initial'),
        ('AuthenticationApp', '0002_auto_20161126_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.Course'),
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
