# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_auto_20161201_1452'),
        ('CompaniesApp', '0001_initial'),
        ('GroupsApp', '0002_group_project'),
        ('AuthenticationApp', '0004_auto_20161130_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='companies',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='projects',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project'),
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
    ]
