# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_auto_20170125_1613'),
        ('AuthenticationApp', '0005_auto_20170204_2218'),
    ]

    operations = [
    ]
