# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_engineer_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
