# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0007_auto_20161125_1552'),
        ('AuthenticationApp', '0006_auto_20161125_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
