# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_merge_20170213_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enigneer', to='CompaniesApp.Company'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student', to='UniversitiesApp.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='UniversitiesApp.University'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, to='UniversitiesApp.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='UniversitiesApp.University'),
        ),
    ]
