# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_auto_20170306_0048'),
        ('AuthenticationApp', '0008_auto_20170213_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.ManyToManyField(related_name='student_set', to='ProjectsApp.ProgrammingLanguage'),
        ),
    ]
