# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSCapstoneApp', '__first__'),
        ('AuthenticationApp', '0009_student_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='languages',
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(related_name='student_set', to='CSCapstoneApp.SkillTag'),
        ),
    ]
