# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversitiesApp', '0005_auto_20161126_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('university', models.ManyToManyField(to='UniversitiesApp.University')),
            ],
        ),
    ]
