# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University')),
            ],
        ),
    ]
