# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0003_course_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='photo',
            field=models.ImageField(blank=True, default=b'static/universityimages/purdue.jpg', null=True, upload_to=b'static/universityimages'),
        ),
    ]
