# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0004_auto_20161108_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.RemoveField(
            model_name='university',
            name='members',
        ),
    ]
