# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0004_auto_20161108_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(to='AuthenticationApp.Student'),
        ),
        migrations.AlterField(
            model_name='university',
            name='members',
            field=models.ManyToManyField(to='AuthenticationApp.Student'),
        ),
    ]
