# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_auto_20161125_1517'),
        ('UniversitiesApp', '0005_auto_20161125_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(to='AuthenticationApp.Professor'),
        ),
    ]
