# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_auto_20161201_0139'),
        ('UniversitiesApp', '0005_auto_20161114_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
