# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0006_course_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='university',
            name='members',
        ),
    ]
