# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0006_auto_20170213_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='website',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='UniversitiesApp.University'),
        ),
    ]
