# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0007_auto_20170213_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='UniversitiesApp.University'),
        ),
    ]
