# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_remove_student_university'),
        ('UniversitiesApp', '0007_auto_20161125_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(to='AuthenticationApp.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='AuthenticationApp.Student'),
        ),
        migrations.AddField(
            model_name='university',
            name='studetns',
            field=models.ManyToManyField(to='AuthenticationApp.Student'),
        ),
    ]
