# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0008_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
