# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniversitiesApp', '0004_auto_20161108_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default=0, upload_to='static/teacherimages')),
                ('email', models.CharField(max_length=300)),
                ('courses', models.ManyToManyField(to='UniversitiesApp.Course')),
            ],
        ),
    ]
