# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('university', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
