# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0004_auto_20161108_1557'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_map',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
